### ISSUE TITLE
Request for original zip file

### ISSUE THREAD

**Issue by rawteech** [JMitnik/CMS_Edwin#1]
Hi @JMitnik , could you still be having the original zip file of the CMS_template that you downloaded? I would be really glad if you shared it with me. Thanks

**Comment by JMitnik** [comment]
Hi @rawteech,

Unfortunately, it is not mine to share. I got it from a Udemy course by Edwin Diaz, and this is all I have. Maybe you can find more about it om his "PHP for beginners course", it has very often discounts
